# -*- coding: utf-8 -*-
import io

T = chr(96) * 3  # triple backtick
L = []
L.append('# Cybersight Malware Samples - 全家族逆向分析报告')
L.append('')
L.append('## 执行摘要')
L.append('')
L.append('基于 reverse-skill v2 工作流，对 Cybersight Security Malware-Samples 仓库的 79 个恶意软件家族进行系统化逆向分析。')
L.append('')
L.append('**分析范围**：79 家族 / 92 样本 / 44 编译与壳识别 / 8 深度逆向 / 28 条 Evidence')
L.append('')
L.append('## 一、编译器和壳分布')
L.append('')
L.append('| 编译器/壳 | 家族 |')
L.append('|---|---|')
L.append('| MSVC (VS2002-2017) | 20+ |')
L.append('| .NET CLR | 12 |')
L.append('| Delphi | 4 (DarkComet, Pony, FakeAV, Neshta) |')
L.append('| UPX | 8+ (Vidar, XMRig, Azorult, WarzoneRAT) |')
L.append('| NSIS | 5 (GULoader, Quasar, WarzoneRAT, 888RAT, GULoader) |')
L.append('| AutoIt EA06 | 2 (888RAT, HawkEye) |')
L.append('| VMProtect | 2 (TrickBot, LockBit) |')
L.append('| MEW | 2 (Vidar, Quasar) |')
L.append('| pkr_ce1a | 2 (StealC, Lumma) |')
L.append('| ELF | 2 (Mirai, Gafgyt) |')
L.append('| SmartAssembly | 1 (AgentTesla 内层) |')
L.append('')
L.append('## 二、NJRAT 完整逆向')
L.append('')
L.append('- MD5: b54802ccdd1ae31f129f6caabdb92f45')
L.append('- 脱壳成功：从 1 个函数恢复到 188 函数')
L.append('- 加密：两把 4 字节 XOR key (.text / .data 分别加密)')
L.append('- key1 = 0x4F1E597C (.text, 0x401000-0x408F6C)')
L.append('- key2 = 0x29C73795 (.data, 0x42B000-0x42E3D0)')
L.append('- Builder 指纹：KingKarton_10')
L.append('- C2 服务器：30 个 (crutop.nu / crutop.ru / mazafaka.ru 等)')
L.append('- 关键能力：键盘记录 / 屏幕监控 / 网页注入 / 银行钓鱼 / 进程注入 / 持久化')
L.append('- ATT&CK: T1059, T1071, T1095, T1105, T1112, T1129, T1547.001')
L.append('')
L.append('## 三、AgentTesla 双阶段加载器')
L.append('')
L.append('### 外层 (伪装)')
L.append('')
L.append('- MD5: ef5c6625bdf2a53a6a4ca841cc5868df')
L.append('- 伪装成 Panda Cafe 咖啡/蛋糕订餐 GUI')
L.append('- 4 个 WinForms 界面：Cakes / Coffee / Sandwich / Form1')
L.append('')
L.append('### 内层加载逻辑')
L.append('')
L.append('- 从资源读取 ZH 加密载荷')
L.append('- 22 字节 XOR key：548BHE35Z8SH7888GSBYD9')
L.append('- 解密算法：out[i] = ((in[i] ^ key[i%22]) - in[(i+1)%n] + 256) & 0xFF')
L.append('- Assembly.Load 反射加载')
L.append('- GetTypes()[9] + Activator.CreateInstance 执行')
L.append('')
L.append('### 内层 payload')
L.append('')
L.append('- MD5: 53106229a87e970b8befe76d9118f647')
L.append('- 保护器：SmartAssembly 7.3.0.3296')
L.append('- 方法：254 (107 bodyless)')
L.append('- 字符串加密：每字符串 XOR (32 位魔数分 4 通道)')
L.append('- 嵌入资源 GUID：{07eefa3e-4bba-4508-ab41-20404168e31b}')
L.append('')
L.append('## 四、其他深度分析')
L.append('')
L.append('### DarkComet')
L.append('- Delphi 编写 / DCMUTEX 互斥体')
L.append('- 12 类远控命令 (TIVEREMOTESHELL / TLOGSHISTORY / TMONITORS)')
L.append('')
L.append('### Pony')
L.append('- C2：http://don.service-master.eu/gate.php')
L.append('- 下载源：http://don.service-master.eu/shit.exe')
L.append('- FTP/SMTP/IMAP/POP3 凭据窃取')
L.append('')
L.append('### Akira 勒索')
L.append('- ChaCha20 加密 (expand 32-byte k)')
L.append('- Tor 面板：akiral2iz6a7qgd3ayp3l6yub7xx2uep76idk3u2kollpj5z3z636bad.onion')
L.append('- 加密扩展名：.akira')
L.append('')
L.append('### MonsterV2 勒索')
L.append('- Delphi 编写 / Tor 面板：monste3rxfp2f7g3i.onion/gGj')
L.append('')
L.append('### Mirai IoT 僵尸网络')
L.append('- ELF 二进制 / C2：198.211.113.55')
L.append('- 特征：POST /ctrlt/DeviceUpgrade_1 HTTP/1.1')
L.append('')
L.append('### Gafgyt IoT 僵尸网络')
L.append('- ELF / C2：185.244.25.211, 8.8.8.8')
L.append('')
L.append('### BlackMoon (XiaoBa 挖矿 + 银行木马)')
L.append('- CoinHive 挖矿：yuNWeGn9GWL72dONBX9WNEj1aVHxg49E')
L.append('- 内嵌 PE @ 0x35828 + XOR 字符串解码 + API 哈希解析')
L.append('')
L.append('### XMRig (挖矿)')
L.append('- UPX 脱壳：1.5MB → 2.4MB')
L.append('- 矿池：donate.v2.xmrig.com')
L.append('')
L.append('### Azorult')
L.append('- UPX 脱壳：7.6MB → 8.2MB')
L.append('')
L.append('### Nanocore')
L.append('- .NET CLR v2.0.50727 / 401 方法 (63 bodyless)')
L.append('- 关键方法：AddHostEntry / RebuildHostCache / SendToServer / DisableProtection')
L.append('- 使用 Socket / Rijndael / MD5')
L.append('')
L.append('### Redline')
L.append('- 内存 dump / 520KB / Chrome 浏览器凭据窃取')
L.append('')
L.append('### WSHRAT')
L.append('- 1.2MB 混淆 JS / 13978 条字符串数组')
L.append('- 通过 PowerShell 下载后续载荷')
L.append('')
L.append('### SnakeKeyLogger')
L.append('- 伪装成 DVLD_Buisness (驾照管理系统)')
L.append('- .NET CLR v4.0.30319 / 529 方法')
L.append('- SQL 相关字符串 (Applications / DetainedLicenses / Drivers)')
L.append('')
L.append('### GoldenEye')
L.append('- JS 下载器 (374KB) + PE 载荷 (260KB)')
L.append('- JS: ActiveXObject + Scripting.FileSystemObject')
L.append('')
L.append('### BadRabbit')
L.append('- VM 检测 (CPUID 0x40000000) + XOR 字符串解码')
L.append('')
L.append('### FakeAV')
L.append('- Delphi + UPX 壳')
L.append('- URL：universal101.com/upd.sc / upd02.app / gomyron.com')
L.append('')
L.append('### NotPetya')
L.append('- BTC：1Mz7153HMuxXTuR2R1t78mGSdzaAtNbBWX')
L.append('- 邮箱：wowsmith123456@posteo.net')
L.append('')
L.append('### CobaltStrike')
L.append('- C2：s3.us-east-2.amazonaws.com/cumulodirifiuti/pieghevole.zip')
L.append('- IP：3.120.209.58')
L.append('')
L.append('### Ploutus (ATM 恶意软件)')
L.append('- .NET 编写 / ATM 相关 API 引用 29 次')
L.append('')
L.append('### 888RAT')
L.append('- AutoIt EA06 加密脚本 + NSIS 3.09 打包 / 40MB')
L.append('- EA06 标记：0xd341c / 0x26626b7')
L.append('- 非标准 LZMA，需专用工具 (myAut2Exe)')
L.append('')
L.append('### Quasar')
L.append('- NSIS + MEW 壳 / 19MB')
L.append('- C# RAT / 提取出 19MB .NET payload')
L.append('')
L.append('### PrivateLoader')
L.append('- 13MB / MSVC VS2017')
L.append('- C2：pdf-suite.com 系列 (14 URLs)')
L.append('- BTC：3FKjC4EVzSSJzomNYA5w3fCoQzxz50MHw3')
L.append('')
L.append('### WarzoneRAT')
L.append('- 双层壳：UPX + ASPack')
L.append('')
L.append('## 五、IOC 汇总')
L.append('')
L.append('### 5.1 C2 / 服务器')
L.append(T)
L.append('NJRAT (30):  crutop.nu / crutop.ru / mazafaka.ru / color-bank.ru / asechka.ru')
L.append('             trojan.ru / fuck.ru / goldensand.ru / filesearch.ru / devx.nm.ru')
L.append('             ros-neftbank.ru / lovingod.host.sk / cvv.ru / hackers.lv / fethard.biz')
L.append('             ldark.nm.ru / gaz-prom.ru / promo.ru / potleaf.chat.ru / kadet.ru')
L.append('             xware.cjb.net / konfiskat.org / parex-bank.ru / kidos-bank.ru / kavkaz.ru')
L.append('Pony:          don.service-master.eu')
L.append('Imminent:      195.22.127.105')
L.append('Mirai:         198.211.113.55')
L.append('Gafgyt:        185.244.25.211')
L.append('BlackMoon:     124.40.51.17 / 58.17.236.92 / 60.210.176.251')
L.append('CobaltStrike:  3.120.209.58 / cumulodirifiuti/pieghevole.zip')
L.append('Upatre:        94.23.247.202')
L.append('FakeAV:        universal101.com / gomyron.com')
L.append('PrivateLoader: pdf-suite.com (14 URLs)')
L.append(T)
L.append('')
L.append('### 5.2 加密货币钱包')
L.append(T)
L.append('NotPetya BTC:       1Mz7153HMuxXTuR2R1t78mGSdzaAtNbBWX')
L.append('PrivateLoader BTC:  3FKjC4EVzSSJzomNYA5w3fCoQzxz50MHw3')
L.append('BlackMoon CoinHive: yuNWeGn9GWL72dONBX9WNEj1aVHxg49E')
L.append(T)
L.append('')
L.append('### 5.3 注册表持久化')
L.append(T)
L.append('NJRAT:       ShellServiceObjectDelayLoad')
L.append('             IE Setup/Setup -> Path')
L.append('             .DEFAULT/.../Explorer/BrowseNewProcess')
L.append('             Internet Settings/Zones/%u')
L.append('DarkComet:   MSConfig/startupreg')
L.append('             Windows NT/CurrentVersion/Winlogon')
L.append('             CurrentVersion/Run')
L.append(T)
L.append('')
L.append('## 六、MITRE ATT&CK 映射')
L.append('')
L.append('| Tactic | Technique | 样本 |')
L.append('|---|---|---|')
L.append('| Execution | T1059 命令行 | NJRAT / DarkComet / GoldenEye |')
L.append('| Execution | T1106 原生 API | NJRAT / BadRabbit |')
L.append('| Persistence | T1547.001 注册表 Run | NJRAT / DarkComet |')
L.append('| Persistence | T1112 修改注册表 | NJRAT / DarkComet / BlackMoon |')
L.append('| Defense Evasion | T1027 混淆文件 | NJRAT / BadRabbit / BlackMoon / AgentTesla |')
L.append('| Defense Evasion | T1027.007 API 哈希 | BlackMoon |')
L.append('| Defense Evasion | T1027.009 嵌入载荷 | NJRAT / BlackMoon / AgentTesla |')
L.append('| Defense Evasion | T1055 进程注入 | NJRAT |')
L.append('| Defense Evasion | T1497.001 VM 检测 | BadRabbit |')
L.append('| Defense Evasion | T1497.002 反调试 | NJRAT / BlackMoon / FakeAV |')
L.append('| Credential Access | T1056.001 键盘记录 | NJRAT / DarkComet / BlackMoon |')
L.append('| Credential Access | T1555 浏览器凭据 | Pony / Redline / PrivateLoader |')
L.append('| Collection | T1185 浏览器会话劫持 | NJRAT |')
L.append('| Collection | T1113 屏幕捕获 | NJRAT / DarkComet |')
L.append('| C2 | T1071 应用层协议 | 全部 RAT |')
L.append('| C2 | T1573 加密信道 | Akira / CobaltStrike |')
L.append('| Impact | T1486 数据加密 | Akira / MonsterV2 / LockBit / NotPetya / AvosLocker |')
L.append('| Impact | T1496 资源劫持 | XMRig / BlackMoon |')
L.append('')
L.append('## 七、Evidence 索引')
L.append('')
L.append('| ID | 标题 |')
L.append('|---|---|')
L.append('| E-001 | NJRAT XOR 解密还原 188 函数 |')
L.append('| E-002 | NJRAT .data 段提取 30 个 C2 |')
L.append('| E-003 | 生成 15 YARA + 12 Sigma 规则 |')
L.append('| E-004 | XMRig UPX 脱壳 (1.5MB->2.4MB) |')
L.append('| E-005 | Azorult UPX 脱壳 (7.6MB->8.2MB) |')
L.append('| E-006 | 888RAT NSIS+AutoIt EA06 识别 |')
L.append('| E-007 | Mirai ELF C2 (198.211.113.55) |')
L.append('| E-008 | Gafgyt ELF C2 (185.244.25.211) |')
L.append('| E-009 | 888RAT AutoIt EA06 结构确认 |')
L.append('| E-010 | Quasar NSIS+MEW 分析 |')
L.append('| E-011 | XMRig donate.v2.xmrig.com 配置 |')
L.append('| E-012 | PrivateLoader 13MB pdf-suite.com C2 |')
L.append('| E-013 | Vidar memory dump 分析 |')
L.append('| E-014 | Lumma/Raccoon/StealC pkr_ce1a 壳 |')
L.append('| E-015 | WarzoneRAT UPX+ASPack 双层壳 |')
L.append('| E-016 | Quasar NSIS 提取 19MB .NET payload |')
L.append('| E-017 | AgentTesla PAGO.exe .NET CLR 确认 |')
L.append('| E-018 | 888RAT EA06 非标准 LZMA |')
L.append('| E-019 | Vidar 22K 字符串分析 |')
L.append('| E-020 | AgentTesla 双阶段加载器反向 |')
L.append('| E-021 | 提取 AgentTesla 隐藏 PE (67072 字节) |')
L.append('| E-022 | AgentTesla XOR key 548BHE35Z8SH7888GSBYD9 |')
L.append('| E-023 | AgentTesla 内层 SmartAssembly 7.3 |')
L.append('| E-024 | AgentTesla payload 字符串 XOR + DEFLATE |')
L.append('| E-025 | AgentTesla 嵌入资源 GUID |')
L.append('| E-026 | Nanocore 401 方法反编译 |')
L.append('| E-027 | SnakeKeyLogger 529 方法反编译 (伪装 DVLD) |')
L.append('| E-028 | WSHRAT 1.2MB 混淆 / 13978 字符串数组 |')
L.append('')
L.append('## 八、未完成事项')
L.append('')
L.append('1. 888RAT EA06 脚本解密 (非标准 LZMA)')
L.append('2. Quasar MEW 壳脱壳')
L.append('3. TrickBot / LockBit VMProtect devirt')
L.append('4. WarzoneRAT 双层壳 (UPX + ASPack)')
L.append('5. AgentTesla SmartAssembly 字符串解密')
L.append('6. PrivateLoader 13MB 深度拆分')
L.append('7. Vidar / Lumma / Raccoon pkr_ce1a 壳')
L.append('')
L.append('---')
L.append('')
L.append('*本报告由 reverse-skill v2 工作流 + disrobe 0.10.6 生成*')
L.append('*分析日期：2026-10-04*')
L.append('')

content = '\n'.join(L)
path = r'C:\\Users\\洛天依\\Desktop\\新建文件夹\\逆向\\恶俗样本\\分析\\REVERSE_REPORT.md'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written: ' + path)
print('Chars: ' + str(len(content)))
print('Lines: ' + str(content.count(chr(10))))